[package]
name = "neotrade"
version = "0.1.0"
authors = ["peter <peter.hall@algomi.com>"]

[dependencies]
serde_json = "1.0"
serde = "1.0.15"
serde_derive = "1.0.15"
toml = "0.4"
futures = "0.1"
reqwest = "0.7.3"